# nginx reverse proxy configuration for LP web frontend & bytebin/bytesocks backend
server {
	listen 80 default_server;

	# proxy '/' path to LPW frontend
	location / {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $server_name;

		proxy_pass http://frontend;
	}

	# disable bytebin frontend
	location = /data/ {
		return 404;
	}

	# proxy '/data' path to bytebin backend
	location /data/ {
		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $server_name;

		proxy_pass http://bytebin:8080/;
	}

	# proxy '/ws' path to bytesocks backend
	location /ws/ {
		proxy_pass http://bytesocks:8080/;
		proxy_http_version 1.1;

		proxy_set_header Upgrade $http_upgrade;
		proxy_set_header Connection "Upgrade";

		proxy_set_header Host $host;
		proxy_set_header X-Real-IP $remote_addr;
		proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
		proxy_set_header X-Forwarded-Host $server_name;

		proxy_read_timeout 86400;
		proxy_send_timeout 86400;
	}
}
